#!/usr/bin/python2 -S
# -*- coding: utf-8 -*-
import sys
reload(sys)
sys.setdefaultencoding("utf-8")

import site
import traceback
import codecs
import os
import sqlite3
#import pprint

import his_loader
import db_operator


def main():

    try:
        # connect to DB 
        conn = db_operator.get_db_conn()
        dbcur = conn.cursor()
        inventory_ranges = db_operator.get_inventory(dbcur)

        # real stuff
        his_loader.load_some("Bank.txt.utf8", dbcur, inventory_ranges)
        
        # DB clean up
        dbcur.close()
        conn.commit()
        conn.close()

    except  Exception as e:
        #pp = pprint.PrettyPrinter(indent=4)
        #pp.pprint(e) 
        
        (t, v, bt) = sys.exc_info()
        traceback.print_exception(t, v, bt)

        print
        print e

        conn.close()
        return 1


    return 0

if __name__ == "__main__":

    r = main()
    sys.exit(r)


